### ISSUE TITLE
Action fails when files are identical

### ISSUE THREAD

**Issue by bblanchon** [leigholiver/commit-with-deploy-key#2]
Hi,

Thank you very much for creating this action.
I find deploy keys better than personal access tokens because they allow you to give access to one repo only.

I noticed that if you use the action to push files that are identical to the files on the destination repo, it fails the build with the following  message:

    nothing to commit, working tree clean

I think that pushing identical files is a valid use case.
It happens any time a build is triggered by a change that doesn't affect the files that you push; for example, when you edit the README of the source repo.

I suppose that some users might want to see an error in that case, so maybe we'd need a flag to specify the behavior

Best regards,
Benoit

**Comment by leigholiver** [comment]
Hi, thanks for raising the bug.
I've just released version `v1.0.3` which should fix this.
Cheers

**Comment by bblanchon** [comment]
I just tested and I can confirm that it works.
Thanks, @leigholiver!
